[package]
name = "mqpro-blink"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
